name: Generate Changelog

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Trigger only on new tags starting with 'v'

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
  
