name: Auto Release

on:
  push:
    tags:
      - 'v*' # Change 'main' to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest # You can use other runners like macOS or Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/workflows/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }} # Specify the version number you want to release
          release_name: Release ${{ github.ref }}
          body: |
            Add release notes here
            You can also include links to the artifacts like mvn jar and pypi package.
            ${{steps.build_changelog.outputs.changelog}}
          draft: false

      # Add steps here to upload any additional artifacts (e.g., mvn jar, pypi package, etc.) if required.